In [163]:
import re
import pandas as pd
import numpy as np

In [164]:
dataset=pd.read_csv("Reviews.csv")

In [165]:
dataset.head()

,asin,name,rating,date,verified,title,body,helpfulVotes
0,B0000SX2UC,Janet,3,"October 11, 2005",False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1.0
1,B0000SX2UC,Luke Wyatt,1,"January 7, 2004",False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,17.0
2,B0000SX2UC,Brooke,5,"December 30, 2003",False,Love This Phone,"This is a great, reliable phone. I also purcha...",5.0
3,B0000SX2UC,amy m. teague,3,"March 18, 2004",False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1.0
4,B0000SX2UC,tristazbimmer,4,"August 28, 2005",False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1.0

In [166]:
dataset.isnull().sum()

asin                0
name                2
rating              0
date                0
verified            0
title              14
body               21
helpfulVotes    40771
dtype: int64

In [167]:
dataset['body'] = dataset['body'].fillna('').apply(str)
dataset['name'] = dataset ['name'].fillna('').apply(str)
dataset['title'] = dataset['title'].fillna('').apply(str)
dataset['helpfulVotes'] = dataset ['helpfulVotes'].fillna('').apply(str)

In [168]:
dataset.isnull().sum()

asin            0
name            0
rating          0
date            0
verified        0
title           0
body            0
helpfulVotes    0
dtype: int64

In [169]:
dataset=dataset.drop(columns=['asin','name','helpfulVotes','date'],axis=1)

In [170]:
a=dataset['rating'].tolist()
a

[3,
 1,
 5,
 3,
 4,
 4,
 5,
 4,
 5,
 3,
 4,
 1,
 2,
 4,
 1,
 4,
 5,
 1,
 5,
 1,
 5,
 4,
 1,
 1,
 5,
 3,
 4,
 1,
 5,
 3,
 1,
 5,
 5,
 5,
 5,
 4,
 4,
 5,
 5,
 4,
 4,
 3,
 4,
 4,
 1,
 5,
 5,
 1,
 5,
 4,
 1,
 5,
 5,
 1,
 4,
 1,
 5,
 5,
 5,
 1,
 1,
 5,
 1,
 5,
 4,
 5,
 3,
 5,
 3,
 5,
 5,
 2,
 3,
 1,
 5,
 4,
 3,
 1,
 4,
 1,
 3,
 4,
 3,
 2,
 4,
 3,
 4,
 3,
 2,
 5,
 2,
 5,
 1,
 4,
 3,
 4,
 1,
 5,
 5,
 5,
 3,
 4,
 2,
 3,
 4,
 1,
 5,
 1,
 1,
 2,
 4,
 5,
 1,
 5,
 1,
 5,
 3,
 4,
 5,
 3,
 2,
 1,
 3,
 5,
 5,
 2,
 3,
 5,
 1,
 1,
 4,
 5,
 3,
 5,
 2,
 1,
 3,
 3,
 5,
 1,
 1,
 5,
 1,
 1,
 5,
 5,
 3,
 4,
 3,
 3,
 1,
 5,
 5,
 1,
 1,
 2,
 4,
 1,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 5,
 2,
 4,
 5,
 1,
 4,
 5,
 5,
 3,
 1,
 5,
 5,
 5,
 5,
 1,
 2,
 5,
 1,
 5,
 1,
 3,
 1,
 1,
 3,
 5,
 4,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 4,
 1,
 5,
 2,
 1,
 5,
 5,
 5,
 1,
 1,
 5,
 1,
 5,
 3,
 5,
 1,
 5,
 1,
 4,
 4,
 1,
 3,
 1,
 5,
 1,
 5,
 5,
 4,
 1,
 1,
 2,
 1,
 5,
 1,
 3,
 1,
 1,
 1,
 5,
 5,
 5,
 2,
 5,
 2,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 5,
 5,
 5,
 5,
 1,
 5,
 5,
 5,
 5,
 1,
 5,
 3,
 2,
 1,
 2,
 5,
 5,
 5,
 1,
 3,
 5,
 1,
 5,
 4,
 1,
 5,
 1,
 5,
 1,
 5,
 5,
 1,
 1,
 5,
 5,
 5,
 2,
 5,
 3,
 5,
 5,
 5,
 3,
 5,
 5,
 5,
 5,
 3,
 5,
 4,
 4,
 3,
 2,
 3,
 4,
 2,
 5,
 5,
 5,
 5,
 4,
 3,
 5,
 5,
 5,
 4,
 4,
 3,
 4,
 4,
 4,
 5,
 1,
 1,
 3,
 4,
 5,
 1,
 1,
 2,
 1,
 1,
 2,
 5,
 5,
 5,
 5,
 1,
 5,
 5,
 2,
 1,
 5,
 1,
 5,
 1,
 5,
 3,
 5,
 5,
 5,
 2,
 1,
 1,
 5,
 3,
 2,
 5,
 4,
 1,
 1,
 5,
 3,
 4,
 1,
 5,
 1,
 5,
 4,
 5,
 2,
 4,
 1,
 4,
 5,
 5,
 5,
 2,
 4,
 1,
 5,
 1,
 1,
 3,
 3,
 3,
 3,
 5,
 5,
 4,
 2,
 4,
 5,
 4,
 3,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 3,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 2,
 4,
 5,
 5,
 5,
 1,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 5,
 1,
 2,
 5,
 5,
 4,
 4,
 2,
 4,
 4,
 1,
 4,
 4,
 4,
 5,
 5,
 1,
 5,
 2,
 5,
 2,
 1,
 4,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 1,
 3,
 5,
 5,
 5,
 5,
 1,
 4,
 2,
 5,
 3,
 5,
 5,
 1,
 3,
 5,
 5,
 5,
 1,
 1,
 5,
 5,
 5,
 4,
 5,
 3,
 5,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 3,
 4,
 5,
 5,
 5,
 4,
 5,
 5,
 4,
 5,
 3,
 1,
 5,
 4,
 5,
 1,
 1,
 3,
 5,
 1,
 2,
 5,
 5,
 2,
 5,
 3,
 1,
 5,
 5,
 1,
 2,
 5,
 3,
 1,
 1,
 3,
 5,
 5,
 3,
 3,
 1,
 1,
 5,
 5,
 1,
 3,
 5,
 5,
 1,
 5,
 5,
 1,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 3,
 5,
 5,
 5,
 3,
 4,
 5,
 5,
 3,
 5,
 1,
 1,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 3,
 5,
 2,
 5,
 5,
 1,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 4,
 5,
 1,
 5,
 4,
 5,
 5,
 5,
 5,
 5,
 4,
 1,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 1,
 5,
 5,
 4,
 4,
 5,
 1,
 5,
 3,
 5,
 5,
 5,
 5,
 2,
 4,
 5,
 5,
 5,
 5,
 3,
 5,
 5,
 5,
 5,
 1,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 2,
 3,
 2,
 5,
 5,
 5,
 5,
 5,
 3,
 1,
 5,
 4,
 5,
 2,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 1,
 3,
 4,
 1,
 3,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 1,
 4,
 5,
 5,
 2,
 1,
 5,
 5,
 5,
 1,
 5,
 4,
 5,
 1,
 1,
 1,
 1,
 1,
 4,
 5,
 3,
 1,
 1,
 2,
 5,
 5,
 4,
 1,
 5,
 5,
 5,
 4,
 1,
 5,
 3,
 5,
 4,
 1,
 5,
 5,
 1,
 1,
 1,
 4,
 3,
 5,
 4,
 5,
 1,
 5,
 5,
 4,
 4,
 5,
 1,
 4,
 5,
 5,
 1,
 5,
 5,
 5,
 4,
 5,
 1,
 5,
 1,
 1,
 5,
 1,
 2,
 1,
 1,
 1,
 5,
 4,
 1,
 5,
 3,
 5,
 5,
 5,
 3,
 4,
 1,
 2,
 5,
 4,
 5,
 3,
 5,
 5,
 1,
 5,
 4,
 5,
 2,
 5,
 4,
 3,
 1,
 5,
 5,
 5,
 1,
 4,
 1,
 5,
 2,
 1,
 1,
 3,
 3,
 5,
 5,
 2,
 2,
 5,
 4,
 1,
 1,
 1,
 2,
 5,
 1,
 5,
 5,
 4,
 5,
 5,
 4,
 5,
 5,
 2,
 1,
 4,
 2,
 2,
 1,
 3,
 1,
 3,
 5,
 5,
 4,
 4,
 5,
 5,
 5,
 1,
 1,
 5,
 3,
 5,
 2,
 1,
 2,
 5,
 4,
 1,
 1,
 2,
 1,
 1,
 5,
 5,
 1,
 4,
 1,
 3,
 5,
 1,
 4,
 1,
 1,
 5,
 1,
 5,
 3,
 5,
 5,
 1,
 2,
 4,
 1,
 1,
 1,
 3,
 2,
 2,
 4,
 5,
 2,
 3,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 3,
 5,
 5,
 5,
 4,
 1,
 4,
 4,
 5,
 5,
 1,
 5,
 3,
 5,
 1,
 4,
 5,
 5,
 4,
 4,
 1,
 1,
 1,
 5,
 2,
 5,
 1,
 5,
 3,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 1,
 5,
 5,
 1,
 1,
 1,
 5,
 5,
 3,
 5,
 5,
 5,
 1,
 5,
 5,
 3,
 4,
 5,
 5,
 3,
 5,
 5,
 4,
 5,
 5,
 5,
 5,
 1,
 1,
 1,
 5,
 5,
 4,
 4,
 5,
 3,
 3,
 4,
 5,
 4,
 4,
 5,
 3,
 3,
 5,
 4,
 5,
 4,
 1,
 1,
 1,
 1,
 4,
 1,
 5,
 3,
 5,
 1,
 5,
 3,
 4,
 ...]

In [171]:
d=[]
for i in range(len(a)):
    if a[i]>=3:
        d.append(1)
    else:
        d.append(0)
d

[1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 ...]

In [172]:
dt=pd.DataFrame(d,columns=['emotion'])
dt

       emotion
0            1
1            0
2            1
3            1
4            1
...        ...
67981        1
67982        1
67983        1
67984        1
67985        1

[67986 rows x 1 columns]

In [173]:
data1=pd.concat([dataset,dt],axis=1)
data1.head()

,rating,verified,title,body,emotion
0,3,False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1
1,1,False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,0
2,5,False,Love This Phone,"This is a great, reliable phone. I also purcha...",1
3,3,False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1
4,4,False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1

In [174]:
data1.drop(['verified'],axis=1,inplace=True)

In [175]:
data1['Review'] = data1[['title', 'body',]].agg(' '.join, axis=1)

In [176]:
data1.drop(['title','body','rating'],axis=1,inplace=True)

In [177]:
data1.shape

(67986, 2)

In [178]:
x=data1.iloc[:,1].values

In [179]:
y=data1.iloc[:,0].values
y

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [180]:
#import natural language toolkit
import nltk
#import stopwords library to remove stopwords
from nltk.corpus import stopwords
#Library used for stem the words
from nltk.stem.porter import PorterStemmer
#create an object for stemming
ps = PorterStemmer()
#Library used for stem the words
from nltk.stem import WordNetLemmatizer
#create an object for wordnet Lemmatizer
wordnet=WordNetLemmatizer()

In [181]:
#replacing punctuations and numbers using re library
temp =re.sub('[^a-zA-Z]',' ',x[i])
temp=temp.lower()
temp=temp.split()
# creating WordNetLemmatizer object to take main lemma of each word
wordnet = WordNetLemmatizer()
#Loop for Leammatization each word in string array at ith row
temp=[wordnet.lemmatize(word) for word in temp if not word in set( stopwords.words('english'))]
#rejoin all string array elements to create back into a string
temp=' '.join(temp)

In [182]:
corpus=[]
# no of rows to clean
for i in range(len(x)):
    #replacing punctuations and numbers using re library
    temp=re.sub('[^a-zA-Z]', ' ', x[i])

In [183]:
    # convert all text to lower cases
    temp=temp.lower()
    # split to array(default delimiter is " ")
    temp=temp.split()
    # creating WordNetLemmatizer object to take main Lemma of each word
    wordnet = WordNetLemmatizer()
    #Loop for Leammatization each word in string array at ith row
    temp=[wordnet.lemmatize(word) for word in temp if not word in set( stopwords.words('english'))]
    #rejoin all string array elements to create back into a string
    temp=' '.join(temp)
    #append each string to create array of clean text
    corpus.append(temp)

In [184]:
#creating bag of word model
from sklearn.feature_extraction.text import CountVectorizer
#To extract max 2000 feature, "max_features" is attribute to
#experiment with to get better results
cv=CountVectorizer(max_features= 2000)
#z contains vectorized data (independent variable)
z=cv.fit_transform(corpus).toarray()

In [185]:
import pickle
pickle.dump(cv,open('count_vec.pkl','wb'))

In [186]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [187]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [188]:
model = Sequential()

In [189]:
model.add(Dense(units=20, kernel_initializer='uniform', activation='relu', input_dim=12))

In [190]:
model.add(Dense(units=100, kernel_initializer='uniform', activation='relu'))

In [191]:
model.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

In [192]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [193]:
model.save('mymodel.h5') # this will save the weights, for keras h5 is extension

In [196]:
# testing the prediction
y_pred = model.predict(x_test)

ValueError: in user code:

    File "C:\Users\HP\anaconda3\lib\site-packages\keras\engine\training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\HP\anaconda3\lib\site-packages\keras\engine\training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\HP\anaconda3\lib\site-packages\keras\engine\training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\HP\anaconda3\lib\site-packages\keras\engine\training.py", line 2111, in predict_step
        return self(x, training=False)
    File "C:\Users\HP\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\HP\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 253, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'sequential_8' (type Sequential).

    Input 0 of layer "dense_22" is incompatible with the layer: expected min_ndim=2, found ndim=1. Full shape received: (None,)

    Call arguments received by layer 'sequential_8' (type Sequential):
      • inputs=tf.Tensor(shape=(None,), dtype=string)
      • training=False
      • mask=None

In [ ]:
y_p = model.predict(cv.transform([text]))
# saving the model
model.save("zomato_2_analysis.h5")